networks:
  dev:
    driver: 'bridge'
services:
  whitelagoonapi-app:
    image: whitelagoonimage
    depends_on:
      - whitelagoon_db
    ports:
      - "8000:80"
    build: 
      context: .
      dockerfile: dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./wwwroot/images:/app/wwwroot/images  
    networks:
      - dev
  whitelagoon_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks_db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgres/data
    networks:
      - dev
volumes:
  app_data: